version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"   # 브로커 클라이언트용
      - "9093:9093"   # 컨트롤러 통신용
    environment:
      KAFKA_KRAFT_MODE: 'yes'
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - travel-network

  region-service:
    build:
      context: .
      args:
        SERVICE_NAME: region
    container_name: region-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - travel-network

  auth-service:
    build:
      context: .
      args:
        SERVICE_NAME: auth
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_SERVICES_USER_URL=http://user-service:8085
    networks:
      - travel-network

  post-service:
    build:
      context: .
      args:
        SERVICE_NAME: post
    container_name: post-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - region-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - travel-network

  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user
    container_name: user-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - travel-network

  group-service:
    build:
      context: .
      args:
        SERVICE_NAME: group
    container_name: group-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  kafka_data: